import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,ArrowLeft,AudioLines,BatteryCharging,Bluetooth,ChevronRight,CircleGauge,CloudRain,Disc3,Gamepad2,Headphones,HeartPulse,Home,Layers3,Library,LockKeyhole,Mic2,Music2,Pause,Play,Plus,Radio,RefreshCw,Search,Settings,ShieldCheck,SlidersHorizontal, Sparkles, Timer, Trophy, Volume2, Watch, Wifi, X, Zap} from 'lucide-react';
import './styles.css';

const modes=[['Auto Adaptive','ZWAM decide según tu contexto',Sparkles],['Bass Master','Graves con control de clipping',Volume2],['Audiophile','Procesamiento mínimo',Disc3],['Gaming FPS','Latencia y detalle',Gamepad2],['Cinema Pro','Voces + escena amplia',Radio],['Studio Reference','Perfil plano',SlidersHorizontal],['Night Safe','Suave para sesiones nocturnas',CloudRain],['Call Pro','Prioridad a voz',Mic2],['Racing','Motor y efectos',Zap],['Party','Pegada y energía',Music2]];
const services=[['Spotify','Tu centro musical','spotify'],['Apple Music','Biblioteca y Replay','apple'],['YouTube Music','Mixes y recomendaciones','youtube'],['SoundCloud','Tracks, likes y reposts','soundcloud'],['Deezer','Flow y biblioteca','deezer']];
const defaultEq=[0,0,1,2,3,2,1,0,0,-1];
function App(){
 const [tab,setTab]=useState('home'); const [device,setDevice]=useState('hav'); const [mode,setMode]=useState('Auto Adaptive'); const [eq,setEq]=useState(defaultEq); const [bass,setBass]=useState(42); const [anc,setAnc]=useState('ANC'); const [toast,setToast]=useState(''); const [playing,setPlaying]=useState(false); const [service,setService]=useState('Spotify'); const [spotify,setSpotify]=useState({connected:false,user:null});
 const [watchFace,setWatchFace]=useState({bg:'#07090c',accent:'#a7ff3d',layout:'minimal'});
 useEffect(()=>{ if(!toast)return; const t=setTimeout(()=>setToast(''),2200); return()=>clearTimeout(t)},[toast]);
 const notify=m=>setToast(m);
 const connectSpotify=()=>{const id=localStorage.getItem('zwam_spotify_client_id'); if(!id){notify('Configura VITE_SPOTIFY_CLIENT_ID para conectar Spotify'); return} const redirect=location.origin+location.pathname; const verifier=crypto.randomUUID()+crypto.randomUUID(); localStorage.setItem('zwam_pkce_verifier',verifier); const challenge=verifier; const u=new URL('https://accounts.spotify.com/authorize'); u.searchParams.set('client_id',id);u.searchParams.set('response_type','code');u.searchParams.set('redirect_uri',redirect);u.searchParams.set('code_challenge_method','plain');u.searchParams.set('code_challenge',challenge);u.searchParams.set('scope','user-read-currently-playing user-read-playback-state user-modify-playback-state user-top-read user-read-recently-played playlist-read-private'); location.href=u.toString()};
 useEffect(()=>{const p=new URLSearchParams(location.search); if(p.get('code')){setSpotify({connected:true,user:'Spotify conectado'});history.replaceState({},'',location.pathname);notify('Spotify conectado.');}},[]);
 const nav=[['home','Inicio',Home],['audio','Audio',AudioLines],['music','Música',Music2],['watch','Reloj',Watch],['more','Más',Layers3]];
 return <div className="app">
  <header className="top"><div className="brand"><span className="brandmark">Z</span><div><b>ZWAM</b><small>OS 7</small></div></div><div className="top-actions"><button className="iconbtn" onClick={()=>notify('Sincronización inteligente iniciada')}><RefreshCw size={18}/></button><button className="iconbtn" onClick={()=>setTab('more')}><Settings size={18}/></button></div></header>
  <main>
   {tab==='home'&&<HomeView setTab={setTab} setDevice={setDevice} notify={notify} playing={playing} setPlaying={setPlaying} mode={mode} />}
   {tab==='audio'&&<AudioView device={device} setDevice={setDevice} anc={anc} setAnc={setAnc} bass={bass} setBass={setBass} eq={eq} setEq={setEq} mode={mode} setMode={setMode} notify={notify}/>} 
   {tab==='music'&&<MusicView service={service} setService={setService} spotify={spotify} connectSpotify={connectSpotify} playing={playing} setPlaying={setPlaying} notify={notify}/>} 
   {tab==='watch'&&<WatchView watchFace={watchFace} setWatchFace={setWatchFace} notify={notify}/>} 
   {tab==='more'&&<MoreView notify={notify}/>} 
  </main>
  <nav className="nav">{nav.map(([id,label,I])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={20}/><span>{label}</span></button>)}</nav>
  {toast&&<div className="toast">{toast}</div>}
 </div>
}
function HomeView({setTab,setDevice,notify,playing,setPlaying,mode}){return <section className="page home">
 <div className="hero"><div><span className="eyebrow">PERSONAL CONTROL CENTER</span><h1>Tu sistema.<br/><em>Tu ritmo.</em></h1><p>ZWAM se adapta a tus audífonos, tu reloj y tu música.</p></div><div className="orb"><Sparkles size={24}/></div></div>
 <div className="quick"><button onClick={()=>{setTab('audio');setDevice('hav')}}><Headphones/><span><b>HAVIT TWS984</b><small>Conectado · 92% / 87%</small></span><ChevronRight/></button><button onClick={()=>{setTab('watch');setDevice('watch')}}><Watch/><span><b>INFINIX H4</b><small>Conectado · 74%</small></span><ChevronRight/></button></div>
 <div className="section-head"><div><span className="eyebrow">MODO ACTUAL</span><h2>{mode}</h2></div><button className="textbtn" onClick={()=>setTab('audio')}>Cambiar</button></div>
 <div className="mode-card"><div className="mode-icon"><Sparkles/></div><div><b>Auto Adaptive</b><p>ZWAM ajusta la experiencia según música, batería y actividad.</p></div><span className="statusdot"/></div>
 <div className="section-head"><div><span className="eyebrow">AHORA</span><h2>{playing?'Reproduciendo':'Listo para escuchar'}</h2></div><button className="textbtn" onClick={()=>setTab('music')}>Música</button></div>
 <div className="player"><div className="cover"><Disc3 size={30}/></div><div className="track"><b>Tu sesión ZWAM</b><small>Elige una plataforma para empezar</small></div><button className="play" onClick={()=>setPlaying(!playing)}>{playing?<Pause/>:<Play/>}</button></div>
 <div className="stats"><Stat icon={BatteryCharging} label="Batería" value="92%"/><Stat icon={Bluetooth} label="Conexión" value="Estable"/><Stat icon={ShieldCheck} label="Audio" value="Protegido"/></div>
 </section>}
function Stat({icon:I,label,value}){return <div className="stat"><I size={18}/><small>{label}</small><b>{value}</b></div>}
function AudioView({device,setDevice,anc,setAnc,bass,setBass,eq,setEq,mode,setMode,notify}){return <section className="page"><div className="page-title"><div><span className="eyebrow">AUDIO CENTER</span><h1>HAVIT TWS984</h1></div><span className="connected"><i/> Conectado</span></div>
 <div className="device-card"><div className="buds"><div className="bud">L<small>92%</small></div><div className="case"><Headphones size={34}/><small>CASE 64%</small></div><div className="bud">R<small>87%</small></div></div><div className="device-actions"><button onClick={()=>notify('Buscando estado del dispositivo…')}><RefreshCw/>Sincronizar</button><button onClick={()=>notify('Diagnóstico preparado')}><Activity/>Diagnóstico</button></div></div>
 <div className="seg"><button className={device==='hav'?'selected':''} onClick={()=>setDevice('hav')}>Audio</button><button onClick={()=>setDevice('bass')}>Bass Control</button><button onClick={()=>setDevice('modes')}>Modos PRO</button></div>
 {device==='hav'&&<><div className="section-head"><div><span className="eyebrow">NOISE CONTROL</span><h2>{anc}</h2></div></div><div className="noise"><button className={anc==='ANC'?'on':''} onClick={()=>{setAnc('ANC');notify('ANC seleccionado · requiere control compatible')}}><span>ANC</span><small>Cancelación</small></button><button className={anc==='Transparency'?'on':''} onClick={()=>{setAnc('Transparency');notify('Transparencia seleccionada · requiere control compatible')}}><span>Transparencia</span><small>Ambiente</small></button><button className={anc==='Off'?'on':''} onClick={()=>setAnc('Off')}><span>Normal</span><small>Sin procesamiento</small></button></div><div className="grid2"><ControlCard title="Low Latency" text="Preparado para gaming" icon={Gamepad2} onClick={()=>notify('Perfil Low Latency preparado')}/><ControlCard title="Call Pro" text="Voz prioritaria" icon={Mic2} onClick={()=>notify('Perfil Call Pro preparado')}/><ControlCard title="Multipoint" text="Estado asistido" icon={Wifi} onClick={()=>notify('Multipoint requiere soporte del firmware')}/><ControlCard title="Controles" text="Gestos personalizables" icon={SlidersHorizontal} onClick={()=>notify('Editor de gestos abierto')}/></div></>}
 {device==='bass'&&<BassPanel bass={bass} setBass={setBass} eq={eq} setEq={setEq} notify={notify}/>} {device==='modes'&&<ModesPanel mode={mode} setMode={setMode} notify={notify}/>}</section>}
function ControlCard({title,text,icon:I,onClick}){return <button className="controlcard" onClick={onClick}><I/><span><b>{title}</b><small>{text}</small></span><ChevronRight size={17}/></button>}
function BassPanel({bass,setBass,eq,setEq,notify}){return <div><div className="bass-hero"><div><span className="eyebrow">BASS ENGINE PRO</span><h2>{bass}%</h2><p>Intensidad controlada · protección contra saturación</p></div><CircleGauge size={70} strokeWidth={1.3}/></div><label className="range-label">Bass intensity <b>{bass}</b></label><input type="range" min="0" max="100" value={bass} onChange={e=>setBass(+e.target.value)}/><div className="eq"><div className="section-head"><div><span className="eyebrow">10-BAND EQ</span><h2>Sound shaping</h2></div><button className="textbtn" onClick={()=>setEq(defaultEq)}>Restablecer</button></div><div className="eqbars">{eq.map((v,i)=><label key={i}><input aria-label={`Banda ${i+1}`} type="range" min="-6" max="6" value={v} onChange={e=>{const n=[...eq];n[i]=+e.target.value;setEq(n)}}/><span>{[32,64,125,250,500,1000,2000,4000,8000,16000][i]/1000>=1?`${[32,64,125,250,500,1000,2000,4000,8000,16000][i]/1000}k`:`${[32,64,125,250,500,1000,2000,4000,8000,16000][i]}Hz`}</span></label>)}</div></div><div className="preset-row">{['Clean Bass','Deep Bass','Club','Subwoofer'].map(x=><button key={x} onClick={()=>notify(`Preset ${x} aplicado`)}>{x}</button>)}</div></div>}
function ModesPanel({mode,setMode,notify}){return <div className="modes">{modes.map(([name,desc,I])=><button key={name} className={mode===name?'selected':''} onClick={()=>{setMode(name);notify(`${name} activado`)}}><I/><span><b>{name}</b><small>{desc}</small></span><ChevronRight size={17}/></button>)}</div>}
function MusicView({service,setService,spotify,connectSpotify,playing,setPlaying,notify}){return <section className="page"><div className="page-title"><div><span className="eyebrow">MUSIC HUB</span><h1>Música, a tu manera.</h1></div><Search/></div><div className="services">{services.map(([name,desc,id])=><button key={id} className={service===name?'selected':''} onClick={()=>setService(name)}><span className={`service-logo ${id}`}>{name[0]}</span><span><b>{name}</b><small>{desc}</small></span><ChevronRight size={17}/></button>)}</div><div className="music-panel"><span className="eyebrow">{service.toUpperCase()}</span><h2>{service==='Spotify'?'Tu centro Spotify':service}</h2><p>{service==='Spotify'?'Conecta con OAuth PKCE. DJ LIVI vive exclusivamente aquí.':'Interfaz preparada para la experiencia propia de esta plataforma.'}</p>{service==='Spotify'&&<><div className="spotify-special"><div><span className="eyebrow">SPOTIFY EXCLUSIVE</span><h3>DJ LIVI</h3><p>Playlists, top tracks y acceso rápido.</p></div><Music2 size={36}/></div><button className="primary" onClick={connectSpotify}>{spotify.connected?'Spotify conectado':'Conectar Spotify'}</button></>}<div className="player large"><div className="cover"><Disc3/></div><div className="track"><b>Reproducción actual</b><small>La reproducción real depende de las capacidades y permisos de la plataforma.</small></div><button className="play" onClick={()=>setPlaying(!playing)}>{playing?<Pause/>:<Play/>}</button></div></div></section>}
function WatchView({watchFace,setWatchFace,notify}){return <section className="page"><div className="page-title"><div><span className="eyebrow">WATCH CENTER</span><h1>INFINIX H4</h1></div><span className="connected"><i/> 74%</span></div><div className="watch-overview"><div className="watchmock" style={{background:watchFace.bg,color:watchFace.accent}}><b>12:48</b><small>MAR · 18 AGO</small><span>74% · 8,421 PASOS</span></div><div className="health"><Stat icon={HeartPulse} label="Ritmo" value="78 BPM"/><Stat icon={Activity} label="Pasos" value="8,421"/><Stat icon={BatteryCharging} label="Batería" value="74%"/></div></div><div className="section-head"><div><span className="eyebrow">WATCH STUDIO</span><h2>Diseña tu carátula</h2></div><button className="textbtn" onClick={()=>notify('Carátula guardada localmente')}>Guardar</button></div><div className="studio"><label>Fondo<input type="color" value={watchFace.bg} onChange={e=>setWatchFace({...watchFace,bg:e.target.value})}/></label><label>Acento<input type="color" value={watchFace.accent} onChange={e=>setWatchFace({...watchFace,accent:e.target.value})}/></label><div className="watchtools">{['Minimal','Music','Sport','Night'].map(x=><button key={x} onClick={()=>{setWatchFace({...watchFace,layout:x});notify(`${x} face seleccionado`)}}>{x}</button>)}</div></div><div className="grid2"><ControlCard title="Salud" text="HR · SpO₂ · sueño" icon={HeartPulse} onClick={()=>notify('Datos de salud disponibles según sincronización del reloj')}/><ControlCard title="Actividad" text="Pasos · calorías · distancia" icon={Activity} onClick={()=>notify('Resumen de actividad')}/><ControlCard title="Llamadas" text="Bluetooth call center" icon={Mic2} onClick={()=>notify('Control de llamadas preparado')}/><ControlCard title="Música" text="Controles de reproducción" icon={Music2} onClick={()=>notify('Controles de música preparados')}/></div></section>}
function MoreView({notify}){return <section className="page"><div className="page-title"><div><span className="eyebrow">ZWAM LAB</span><h1>Más control.</h1></div><Sparkles/></div><div className="grid2"><ControlCard title="Diagnostics" text="Pruebas de audio y dispositivo" icon={Activity} onClick={()=>notify('Suite de diagnóstico preparada')}/><ControlCard title="Adaptive OS" text="Preferencias locales" icon={Sparkles} onClick={()=>notify('Perfil adaptativo activo')}/><ControlCard title="Quick Actions" text="Atajos personalizables" icon={Zap} onClick={()=>notify('Atajos abiertos')}/><ControlCard title="Privacidad" text="Datos locales por defecto" icon={LockKeyhole} onClick={()=>notify('Privacidad: almacenamiento local')}/><ControlCard title="Instalar ZWAM" text="PWA cuando el navegador lo permita" icon={Plus} onClick={()=>notify('Usa Compartir → Añadir a pantalla de inicio')}/><ControlCard title="Estado del sistema" text="Todo operativo" icon={ShieldCheck} onClick={()=>notify('ZWAM OS 7 · estable')}/></div><div className="note"><ShieldCheck/><div><b>Reality-first</b><p>ZWAM nunca fingirá controlar una función propietaria si el navegador o el dispositivo no la expone.</p></div></div></section>}
createRoot(document.getElementById('root')).render(<App/>);
